apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx-2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - blockchain-explorer.shopgrip.ru
      secretName: shopgrip-tls
  rules:
    - host: blockchain-explorer.shopgrip.ru
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: telegram-bot
                port:
                  number: 80
